# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# ruby encoding: utf-8
Market.create(name: "Aachen", store_id: 66352)
Market.create(name: "Aalen", store_id: 65853)
Market.create(name: "Albstadt", store_id: 66852)
Market.create(name: "Alzey", store_id: 67352)
Market.create(name: "Amberg", store_id: 137953)
Market.create(name: "Ansbach", store_id: 67852)
Market.create(name: "Aschaffenburg", store_id: 65854)
Market.create(name: "Aschaffenburg (City-Galerie)", store_id: 65855)
Market.create(name: "Augsburg-Göggingen", store_id: 66854)
Market.create(name: "Augsburg-Oberhausen", store_id: 66853)
Market.create(name: "Backnang", store_id: 65856)
Market.create(name: "Bad Duerrheim", store_id: 65857)
Market.create(name: "Baden-Baden", store_id: 68352)
Market.create(name: "Bad Kreuznach", store_id: 65858)
Market.create(name: "Bad Neustadt", store_id: 65859)
Market.create(name: "Bayreuth", store_id: 68354)
Market.create(name: "Berlin-Biesdorf", store_id: 68358)
Market.create(name: "Berlin-Charlottenburg", store_id: 68359)
Market.create(name: "Berlin-Eiche", store_id: 68360)
Market.create(name: "Berlin-Gropiusstadt", store_id: 68356)
Market.create(name: "Berlin-Hohenschönhausen", store_id: 68361)
Market.create(name: "Berlin-Mitte", store_id: 68362)
Market.create(name: "Berlin-Neukölln", store_id: 68363)
Market.create(name: "Berlin-Prenzlauer Berg", store_id: 68364)
Market.create(name: "Berlin-Schöneweide", store_id: 68365)
Market.create(name: "Berlin-Spandau", store_id: 68366)
Market.create(name: "Berlin-Steglitz", store_id: 68357)
Market.create(name: "Berlin-Tegel", store_id: 68367)
Market.create(name: "Berlin-Tempelhof", store_id: 68368)
Market.create(name: "Berlin-Waltersdorf", store_id: 68369)
Market.create(name: "Berlin-Wedding", store_id: 68370)
Market.create(name: "Bielefeld", store_id: 70352)
Market.create(name: "Bischofsheim", store_id: 70353)
Market.create(name: "Bochum-Hofstede", store_id: 70354)
Market.create(name: "Bochum-Ruhrpark", store_id: 70355)
Market.create(name: "Bonn", store_id: 137952)
Market.create(name: "Brandenburg an der Havel", store_id: 70852)
Market.create(name: "Braunschweig", store_id: 67355)
Market.create(name: "Bremen (Stuhr/ Groß Mackenstedt)", store_id: 70853)
Market.create(name: "Bremen (Waterfront)", store_id: 70855)
Market.create(name: "Bremen (Weserpark)", store_id: 70854)
Market.create(name: "Bremerhaven", store_id: 71352)
Market.create(name: "Bruchsal", store_id: 70856)
Market.create(name: "Buchholz in der Nordheide", store_id: 70857)
Market.create(name: "Buxtehude", store_id: 70858)
Market.create(name: "Castrop-Rauxel (im Castrop-Park)", store_id: 66855)
Market.create(name: "Chemnitz-Röhrsdorf (im Chemnitz-Center)", store_id: 66857)
Market.create(name: "Chemnitz-Sachsenallee", store_id: 66856)
Market.create(name: "Cottbus", store_id: 66858)
Market.create(name: "Crailsheim", store_id: 66859)
Market.create(name: "Deggendorf", store_id: 66860)
Market.create(name: "Dessau", store_id: 66861)
Market.create(name: "Dietzenbach", store_id: 69852)
Market.create(name: "Donauwoerth", store_id: 67354)
Market.create(name: "Dorsten", store_id: 114452)
Market.create(name: "Dortmund", store_id: 71852)
Market.create(name: "Dresden Centrum-Galerie", store_id: 71853)
Market.create(name: "Dresden-ElbePark", store_id: 76353)
Market.create(name: "Dresden-Kaufpark (im Kaufpark)", store_id: 72352)
Market.create(name: "Duisburg-Großenbaum", store_id: 71855)
Market.create(name: "Duisburg-Marxloh", store_id: 71854)
Market.create(name: "Düsseldorf-Arcaden (Ecke Bachstraße)", store_id: 71856)
Market.create(name: "Düsseldorf-Metrostraße", store_id: 73353)
Market.create(name: "Egelsbach", store_id: 73852)
Market.create(name: "Eislingen", store_id: 73853)
Market.create(name: "Ellwangen", store_id: 73854)
Market.create(name: "Elmshorn", store_id: 83353)
Market.create(name: "Emden", store_id: 67858)
Market.create(name: "Erding", store_id: 76352)
Market.create(name: "Erfurt im Thüringen Park", store_id: 76354)
Market.create(name: "Erfurt T.E.C.", store_id: 76355)
Market.create(name: "Erlangen", store_id: 76356)
Market.create(name: "Eschweiler", store_id: 76357)
Market.create(name: "Essen", store_id: 76358)
Market.create(name: "Esslingen", store_id: 67376)
Market.create(name: "Fellbach (Alte B14)", store_id: 66354)
Market.create(name: "Flensburg", store_id: 66355)
Market.create(name: "Frankfurt-Borsigallee", store_id: 66356)
Market.create(name: "Frankfurt-Nordwestzentrum", store_id: 67356)
Market.create(name: "Freiburg", store_id: 66357)
Market.create(name: "Friedrichshafen ", store_id: 66358)
Market.create(name: "Fulda", store_id: 66359)
Market.create(name: "Giessen", store_id: 66361)
Market.create(name: "Gifhorn", store_id: 134952)
Market.create(name: "Goslar", store_id: 72859)
Market.create(name: "Göttingen", store_id: 72862)
Market.create(name: "Greifswald", store_id: 72860)
Market.create(name: "Gründau-Lieblos", store_id: 72861)
Market.create(name: "Günthersdorf", store_id: 67856)
Market.create(name: "Gütersloh", store_id: 72863)
Market.create(name: "Halberstadt", store_id: 67365)
Market.create(name: "Halle-Peißen", store_id: 72864)
Market.create(name: "Hallstadt-Bamberg", store_id: 68353)
Market.create(name: "Halstenbek", store_id: 77353)
Market.create(name: "Hamburg-Altona", store_id: 77355)
Market.create(name: "Hamburg-Billstedt", store_id: 77352)
Market.create(name: "Hamburg-Harburg", store_id: 75870)
Market.create(name: "Hamburg-Hummelsbüttel (Ring 3)", store_id: 77354)
Market.create(name: "Hamburg-Nedderfeld", store_id: 72865)
Market.create(name: "Hamburg-Oststeinbek", store_id: 76852)
Market.create(name: "Hamburg-Wandsbek", store_id: 72866)
Market.create(name: "Hameln", store_id: 77356)
Market.create(name: "Hannover-Vahrenheide", store_id: 77357)
Market.create(name: "Hannover-Wülfel", store_id: 77358)
Market.create(name: "Heide (im Gewerbegebiet Ost)", store_id: 77359)
Market.create(name: "Heidelberg", store_id: 77360)
Market.create(name: "Heidelberg-Rohrbach", store_id: 77361)
Market.create(name: "Heidenheim (Schloss Arkaden)", store_id: 77362)
Market.create(name: "Heilbronn", store_id: 77363)
Market.create(name: "Henstedt-Ulzburg", store_id: 77364)
Market.create(name: "Heppenheim", store_id: 77365)
Market.create(name: "Herzogenrath", store_id: 77366)
Market.create(name: "Hildesheim", store_id: 77367)
Market.create(name: "Hof", store_id: 77368)
Market.create(name: "Holzminden", store_id: 76359)
Market.create(name: "Homburg (im Saarpfalz-Center)", store_id: 77369)
Market.create(name: "Hückelhoven", store_id: 77370)
Market.create(name: "Idar-Oberstein", store_id: 66363)
Market.create(name: "Ingolstadt", store_id: 67367)
Market.create(name: "Itzehoe", store_id: 66364)
Market.create(name: "Jena", store_id: 77852)
Market.create(name: "Kaiserslautern", store_id: 77854)
Market.create(name: "Karlsfeld", store_id: 133452)
Market.create(name: "Karlsruhe", store_id: 77855)
Market.create(name: "Karlsruhe II", store_id: 77856)
Market.create(name: "Kassel (DEZ Kassel-Shop 62)", store_id: 77857)
Market.create(name: "Kempten-Allgäu", store_id: 77858)
Market.create(name: "Kiel", store_id: 77860)
Market.create(name: "Kirchheim (im Nanz Center)", store_id: 77861)
Market.create(name: "Koblenz", store_id: 77862)
Market.create(name: "Köln-Chorweiler", store_id: 83354)
Market.create(name: "Köln-City", store_id: 77866)
Market.create(name: "Köln-Kalk", store_id: 77867)
Market.create(name: "Köln-Marsdorf", store_id: 77865)
Market.create(name: "Konstanz", store_id: 77863)
Market.create(name: "Krefeld", store_id: 77864)
Market.create(name: "Kulmbach", store_id: 108952)
Market.create(name: "Lahr", store_id: 73352)
Market.create(name: "Landau", store_id: 66362)
Market.create(name: "Landsberg am Lech", store_id: 67854)
Market.create(name: "Landshut", store_id: 67855)
Market.create(name: "Leipzig Höfe am Brühl", store_id: 100952)
Market.create(name: "Leipzig-Paunsdorf", store_id: 75352)
Market.create(name: "Lichtenfels", store_id: 108452)
Market.create(name: "Limburg", store_id: 67857)
Market.create(name: "Lingen", store_id: 75353)
Market.create(name: "Lippstadt", store_id: 109952)
Market.create(name: "Lübeck", store_id: 75359)
Market.create(name: "Ludwigsburg", store_id: 75354)
Market.create(name: "Ludwigshafen-Oggersheim", store_id: 75356)
Market.create(name: "Lüneburg", store_id: 75362)
Market.create(name: "Magdeburg-Bördepark", store_id: 67369)
Market.create(name: "Magdeburg-Pfahlberg", store_id: 75364)
Market.create(name: "Mainz", store_id: 75367)
Market.create(name: "Mannheim", store_id: 67372)
Market.create(name: "Mannheim-Sandhofen", store_id: 67373)
Market.create(name: "Marburg", store_id: 75866)
Market.create(name: "Marktredwitz", store_id: 67374)
Market.create(name: "Meerane", store_id: 75871)
Market.create(name: "Memmingen", store_id: 75874)
Market.create(name: "Meppen", store_id: 122452)
Market.create(name: "Mönchengladbach", store_id: 67375)
Market.create(name: "Mosbach", store_id: 75876)
Market.create(name: "Mühldorf am Inn", store_id: 75878)
Market.create(name: "Mühlheim", store_id: 75879)
Market.create(name: "München-Euroindustriepark", store_id: 75877)
Market.create(name: "München-Haidhausen", store_id: 75881)
Market.create(name: "München-Pasing", store_id: 75880)
Market.create(name: "München-Solln", store_id: 79352)
Market.create(name: "Münster", store_id: 75882)
Market.create(name: "Nagold", store_id: 74352)
Market.create(name: "Neubrandenburg", store_id: 66875)
Market.create(name: "Neuburg an der Donau", store_id: 101452)
Market.create(name: "Neumünster", store_id: 66876)
Market.create(name: "Neunkirchen", store_id: 66877)
Market.create(name: "Neuss", store_id: 66878)
Market.create(name: "Neustadt an der Weinstrasse", store_id: 66879)
Market.create(name: "Neutraubling", store_id: 80352)
Market.create(name: "Neu-Ulm", store_id: 66874)
Market.create(name: "Neuwied", store_id: 66880)
Market.create(name: "Nienburg", store_id: 66881)
Market.create(name: "Nordhausen", store_id: 142452)
Market.create(name: "Nordhorn", store_id: 66882)
Market.create(name: "Nördlingen", store_id: 117952)
Market.create(name: "Nürnberg-Kleinreuth", store_id: 66883)
Market.create(name: "Nürnberg-Langwasser", store_id: 75852)
Market.create(name: "Nürnberg-Schoppersdorf", store_id: 75853)
Market.create(name: "Nürtingen", store_id: 75854)
Market.create(name: "Offenburg", store_id: 75855)
Market.create(name: "Oldenburg", store_id: 75856)
Market.create(name: "Osnabrück-Belm", store_id: 68355)
Market.create(name: "Paderborn", store_id: 75857)
Market.create(name: "Papenburg", store_id: 75858)
Market.create(name: "Passau", store_id: 75859)
Market.create(name: "Peine", store_id: 75860)
Market.create(name: "Pforzheim", store_id: 75861)
Market.create(name: "Pirmasens", store_id: 75862)
Market.create(name: "Plauen", store_id: 77853)
Market.create(name: "Porta Westfalica", store_id: 78352)
Market.create(name: "Potsdam", store_id: 75863)
Market.create(name: "Ravensburg", store_id: 75864)
Market.create(name: "Recklinghausen", store_id: 76853)
Market.create(name: "Regensburg", store_id: 75865)
Market.create(name: "Rendsburg", store_id: 116952)
Market.create(name: "Reutlingen", store_id: 75867)
Market.create(name: "Rheine", store_id: 75868)
Market.create(name: "Riesa", store_id: 133952)
Market.create(name: "Rödental", store_id: 75875)
Market.create(name: "Rosenheim", store_id: 75869)
Market.create(name: "Rostock-Brinckmansdorf", store_id: 75873)
Market.create(name: "Rostock-Sievershagen", store_id: 75872)
Market.create(name: "Saarbrücken Saarterrassen", store_id: 67371)
Market.create(name: "Saarbrücken-Saarbasar", store_id: 75370)
Market.create(name: "Saarlouis", store_id: 75369)
Market.create(name: "Schleswig", store_id: 80353)
Market.create(name: "Schorndorf", store_id: 75368)
Market.create(name: "Schwabach", store_id: 86452)
Market.create(name: "Schwäbisch Gmünd", store_id: 75363)
Market.create(name: "Schwäbisch Hall", store_id: 75361)
Market.create(name: "Schwedt", store_id: 75366)
Market.create(name: "Schweinfurt", store_id: 67370)
Market.create(name: "Schwentinental", store_id: 77859)
Market.create(name: "Schwerin", store_id: 75365)
Market.create(name: "Siegen", store_id: 75360)
Market.create(name: "Sindelfingen", store_id: 67368)
Market.create(name: "Singen", store_id: 75358)
Market.create(name: "Sinsheim", store_id: 75357)
Market.create(name: "Speyer", store_id: 75355)
Market.create(name: "Stade", store_id: 66365)
Market.create(name: "Stadthagen", store_id: 86952)
Market.create(name: "Stralsund", store_id: 74859)
Market.create(name: "Staubing", store_id: 74858)
Market.create(name: "Stuttgart-City", store_id: 74856)
Market.create(name: "Stuttgart-Feuerbach", store_id: 74857)
Market.create(name: "Stuttgart-Vaihingen", store_id: 67366)
Market.create(name: "Sulzbach", store_id: 74855)
Market.create(name: "Traunreut", store_id: 74854)
Market.create(name: "Traunstein", store_id: 67364)
Market.create(name: "Trier", store_id: 74853)
Market.create(name: "Ulm", store_id: 74852)
Market.create(name: "Velbert", store_id: 72858)
Market.create(name: "Viernheim", store_id: 72857)
Market.create(name: "Waiblingen", store_id: 72856)
Market.create(name: "Weiden", store_id: 72855)
Market.create(name: "Weilheim", store_id: 72854)
Market.create(name: "Weiterstadt", store_id: 67353)
Market.create(name: "Wetzlar", store_id: 72853)
Market.create(name: "Wiesbaden-Äppelallee", store_id: 65861)
Market.create(name: "Wiesbaden-Hasengarten", store_id: 72852)
Market.create(name: "Wilhelmshaven", store_id: 83352)
Market.create(name: "Wolfsburg", store_id: 65860)
Market.create(name: "Worms", store_id: 66353)
Market.create(name: "Wuppertal", store_id: 69354)
Market.create(name: "Würzburg", store_id: 69353)
Market.create(name: "Würzburg-Domstrasse", store_id: 68845)
Market.create(name: "Würzburg-Unterdürrbach", store_id: 69352)
Market.create(name: "Zella-Mehlis", store_id: 68853)
Market.create(name: "Zwickau", store_id: 68852)


